// Authentication Actions
export const authenticationAction = {
  USER_LOGIN_INITIATE: "USER_LOGIN_INITIATE",
  SOCIAL_USER_LOGIN_INITIATE: "SOCIAL_USER_LOGIN_INITIATE",
  USER_LOGIN_OTP_SEND: "USER_LOGIN_OTP_SEND",
  USER_LOGIN_OTP_FAIL: "USER_LOGIN_OTP_FAIL",
  USER_LOGIN_SUCCESS: "USER_LOGIN_SUCCESS",
  USER_LOGIN_FAILURE: "USER_LOGIN_FAILURE",

  USER_REGISTER_INITIATE: "USER_REGISTER_INITIATE",
  USER_REGISTER_SUCCESS: "USER_REGISTER_SUCCESS",
  USER_REGISTER_FAILURE: "USER_REGISTER_FAILURE",

  FORGOT_PASSWORD_INITIATE: "FORGOT_PASSWORD_INITIATE",
  FORGOT_PASSWORD_SUCCESS: "FORGOT_PASSWORD_SUCCESS",
  FORGOT_PASSWORD_FAILURE: "FORGOT_PASSWORD_FAILURE",

  FORGOT_LINK_VERIFICATION_INITIATE: "FORGOT_LINK_VERIFICATION_INITIATE",
  FORGOT_LINK_VERIFICATION_SUCCESS: "FORGOT_LINK_VERIFICATION_SUCCESS",
  FORGOT_LINK_VERIFICATION_FAILURE: "FORGOT_LINK_VERIFICATION_FAILURE",

  RESET_PASSWORD_INITIATE: "RESET_PASSWORD_INITIATE",
  RESET_PASSWORD_SUCCESS: "RESET_PASSWORD_SUCCESS",
  RESET_PASSWORD_FAILURE: "RESET_PASSWORD_FAILURE",

  CHANGE_PASSWORD_INITIATE: "CHANGE_PASSWORD_INITIATE",
  CHANGE_PASSWORD_SUCCESS: "CHANGE_PASSWORD_SUCCESS",
  CHANGE_PASSWORD_FAILURE: "CHANGE_PASSWORD_FAILURE",

  USER_PROFILE_INITIATE: "USER_PROFILE_INITIATE",
  USER_PROFILE_SUCCESS: "USER_PROFILE_SUCCESS",
  USER_PROFILE_FAILURE: "USER_PROFILE_FAILURE",

  USER_PROFILE_EDIT_INITIATE: "USER_PROFILE_EDIT_INITIATE",
  USER_PROFILE_EDIT_SUCCESS: "USER_PROFILE_EDIT_SUCCESS",
  USER_PROFILE_EDIT_FAILURE: "USER_PROFILE_EDIT_FAILURE",

  CONTACT_US_FORM_INITIATE: "CONTACT_US_FORM_INITIATE",
  CONTACT_US_FORM_SUCCESS: "CONTACT_US_FORM_SUCCESS",
  CONTACT_US_FORM_FAILURE: "CONTACT_US_FORM_FAILURE",

  USER_LOGOUT: "USER_LOGOUT",

  API_AUTHENTICATION_FAILED: "API_AUTHENTICATION_FAILED",

  DRAWER_EVENT: "DRAWER_EVENT",

  UPDATE_AUTHENTICATION_STATE: "UPDATE_AUTHENTICATION_STATE",

  CLEAR_USER_DATA: "CLEAR_USER_DATA",
};

export const myBookingsAction = {
  GET_TUBE_BOOKINGS_INITIATE: "GET_TUBE_BOOKINGS_INITIATE",
  GET_TUBE_BOOKINGS_SUCCESS: "GET_TUBE_BOOKINGS_SUCCESS",
  GET_TUBE_BOOKINGS_FAILURE: "GET_TUBE_BOOKINGS_FAILURE",

  GET_TRAIN_BOOKINGS_INITIATE: "GET_TRAIN_BOOKINGS_INITIATE",
  GET_TRAIN_BOOKINGS_SUCCESS: "GET_TRAIN_BOOKINGS_SUCCESS",
  GET_TRAIN_BOOKINGS_FAILURE: "GET_TRAIN_BOOKINGS_FAILURE",

  GET_BOOKINGS_DETAILS_INITIATE: "GET_BOOKINGS_DETAILS_INITIATE",
  GET_BOOKINGS_DETAILS_SUCCESS: "GET_BOOKINGS_DETAILS_SUCCESS",
  GET_BOOKINGS_DETAILS_FAILURE: "GET_BOOKINGS_DETAILS_FAILURE",

  CANCEL_BOOKING_INITIATE: "CANCEL_BOOKING_INITIATE",
  CANCEL_BOOKING_SUCCESS: "CANCEL_BOOKING_SUCCESS",
  CANCEL_BOOKING_FAILURE: "CANCEL_BOOKING_FAILURE",

  UPDATE_BOOKINGS_STATE: "UPDATE_BOOKINGS_STATE",

  CLEAR_BOOKINGS_DATA: "CLEAR_BOOKINGS_DATA",
};

export const newBookingsAction = {
  GET_STATIONS_LIST_INITIATE: "GET_STATIONS_LIST_INITIATE",
  GET_STATIONS_LIST_SUCCESS: "GET_STATIONS_LIST_SUCCESS",
  GET_STATIONS_LIST_FAILURE: "GET_STATIONS_LIST_FAILURE",

  SEARCH_TRAINS_LIST_INITIATE: "SEARCH_TRAINS_LIST_INITIATE",
  SEARCH_TRAINS_LIST_SUCCESS: "SEARCH_TRAINS_LIST_SUCCESS",
  SEARCH_TRAINS_LIST_FAILURE: "SEARCH_TRAINS_LIST_FAILURE",

  GET_SELECTED_BOOKING_DETAIL_INITIATE: "GET_SELECTED_BOOKING_DETAIL_INITIATE",
  GET_SELECTED_BOOKING_DETAIL_SUCCESS: "GET_SELECTED_BOOKING_DETAIL_SUCCESS",
  GET_SELECTED_BOOKING_DETAIL_FAILURE: "GET_SELECTED_BOOKING_DETAIL_FAILURE",

  CONFIRM_TRAIN_BOOKING_INITIATE: "CONFIRM_TRAIN_BOOKING_INITIATE",
  CONFIRM_TRAIN_BOOKING_SUCCESS: "CONFIRM_TRAIN_BOOKING_SUCCESS",
  CONFIRM_TRAIN_BOOKING_FAILURE: "CONFIRM_TRAIN_BOOKING_FAILURE",

  UPDATE_NEW_BOOKINGS_STATE: "UPDATE_BOOKINGS_STATE",

  CLEAR_NEW_BOOKINGS_DATA: "CLEAR_BOOKINGS_DATA",
};

export const cardAction = {
  ADD_CARD_DETAILS_INITIATE: "ADD_CARD_DETAILS_INITIATE",
  ADD_CARD_DETAILS_SUCCESS: "ADD_CARD_DETAILS_SUCCESS",
  ADD_CARD_DETAILS_FAILURE: "ADD_CARD_DETAILS_FAILURE",

  REMOVE_CARD_DETAILS_INITIATE: "REMOVE_CARD_DETAILS_INITIATE",
  REMOVE_CARD_DETAILS_SUCCESS: "REMOVE_CARD_DETAILS_SUCCESS",
  REMOVE_CARD_DETAILS_FAILURE: "REMOVE_CARD_DETAILS_FAILURE",

  UPDATE_CARD_DETAILS_STATE: "UPDATE_CARD_DETAILS_STATE",

  CLEAR_CARD_DETAILS_DATA: "CLEAR_CARD_DETAILS_DATA",
};

export const seasonTicketAction = {
  GET_SEASON_TICKET_DETAIL_INITIATE: "GET_SEASON_TICKET_DETAIL_INITIATE",
  GET_SEASON_TICKET_DETAIL_SUCCESS: "GET_SEASON_TICKET_DETAIL_SUCCESS",
  GET_SEASON_TICKET_DETAIL_FAILURE: "GET_SEASON_TICKET_DETAIL_FAILURE",

  REQUEST_SEASON_TICKET_INITIATE: "REQUEST_SEASON_TICKET_INITIATE",
  REQUEST_SEASON_TICKET_SUCCESS: "REQUEST_SEASON_TICKET_SUCCESS",
  REQUEST_SEASON_TICKET_FAILURE: "REQUEST_SEASON_TICKET_FAILURE",

  SEASON_TICKET_UPDATE_PAYMENT_INITIATE:
    "SEASON_TICKET_UPDATE_PAYMENT_INITIATE",
  SEASON_TICKET_UPDATE_PAYMENT_SUCCESS: "SEASON_TICKET_UPDATE_PAYMENT_SUCCESS",
  SEASON_TICKET_UPDATE_PAYMENT_FAILURE: "SEASON_TICKET_UPDATE_PAYMENT_FAILURE",

  SEASON_TICKET_PAYMENT_INITIATE: "SEASON_TICKET_PAYMENT_INITIATE",
  SEASON_TICKET_PAYMENT_SUCCESS: "SEASON_TICKET_PAYMENT_SUCCESS",
  SEASON_TICKET_PAYMENT_FAILURE: "SEASON_TICKET_PAYMENT_FAILURE",

  UPDATE_SEASON_TICKET_STATE: "UPDATE_SEASON_TICKET_STATE",

  CANCEL_SEASON_TICKET_INITIATE: "CANCEL_SEASON_TICKET_INITIATE",

  CLEAR_SEASON_TICKET_DATA: "CLEAR_SEASON_TICKET_DATA",
};

export const flexiTicketAction = {
  GET_FLEXI_TICKET_DETAIL_INITIATE: "GET_FLEXI_TICKET_DETAIL_INITIATE",
  GET_FLEXI_TICKET_DETAIL_SUCCESS: "GET_FLEXI_TICKET_DETAIL_SUCCESS",
  GET_FLEXI_TICKET_DETAIL_FAILURE: "GET_FLEXI_TICKET_DETAIL_FAILURE",

  REQUEST_FLEXI_TICKET_INITIATE: "REQUEST_FLEXI_TICKET_INITIATE",
  REQUEST_FLEXI_TICKET_SUCCESS: "REQUEST_FLEXI_TICKET_SUCCESS",
  REQUEST_FLEXI_TICKET_FAILURE: "REQUEST_FLEXI_TICKET_FAILURE",

  FLEXI_TICKET_UPDATE_PAYMENT_INITIATE: "FLEXI_TICKET_UPDATE_PAYMENT_INITIATE",
  FLEXI_TICKET_UPDATE_PAYMENT_SUCCESS: "FLEXI_TICKET_UPDATE_PAYMENT_SUCCESS",
  FLEXI_TICKET_UPDATE_PAYMENT_FAILURE: "FLEXI_TICKET_UPDATE_PAYMENT_FAILURE",

  FLEXI_TICKET_PAYMENT_INITIATE: "FLEXI_TICKET_PAYMENT_INITIATE",
  FLEXI_TICKET_PAYMENT_SUCCESS: "FLEXI_TICKET_PAYMENT_SUCCESS",
  FLEXI_TICKET_PAYMENT_FAILURE: "FLEXI_TICKET_PAYMENT_FAILURE",

  UPDATE_FLEXI_TICKET_STATE: "UPDATE_FLEXI_TICKET_STATE",

  CLEAR_FLEXI_TICKET_DATA: "CLEAR_FLEXI_TICKET_DATA",
};

export const oysterCardAction = {
  GET_OYSTER_ZONES_LIST_INITIATE: "GET_OYSTER_ZONES_LIST_INITIATE",
  GET_OYSTER_ZONES_LIST_SUCCESS: "GET_OYSTER_ZONES_LIST_SUCCESS",
  GET_OYSTER_ZONES_LIST_FAILURE: "GET_OYSTER_ZONES_LIST_FAILURE",

  OYSTER_CARD_PURCHASE_INITIATE: "OYSTER_CARD_PURCHASE_INITIATE",
  OYSTER_CARD_PURCHASE_SUCCESS: "OYSTER_CARD_PURCHASE_SUCCESS",
  OYSTER_CARD_PURCHASE_FAILURE: "OYSTER_CARD_PURCHASE_FAILURE",

  UPDATE_OYSTER_CARD_STATE: "UPDATE_OYSTER_CARD_STATE",

  CLEAR_OYSTER_CARD_DATA: "CLEAR_OYSTER_CARD_DATA",
};

export const oysterAction = {
  GET_OYSTER_ZONE_LIST_INITIATE: "GET_OYSTER_ZONE_LIST_INITIATE",
  GET_OYSTER_ZONES_LIST_SUCCESS: "GET_OYSTER_ZONES_LIST_SUCCESS",
  GET_OYSTER_ZONES_LIST_FAILURE: "GET_OYSTER_ZONES_LIST_FAILURE",
  GET_OYSTER_ZONES_VALUES_INITIATE: "GET_OYSTER_ZONES_VALUES_INITIATE",
  GET_OYSTER_ZONES_VALUES_SUCCESS: "GET_OYSTER_ZONES_VALUES_SUCCESS",
  OYSTER_CARD_PURCHASE_INITIATES: "OYSTER_CARD_PURCHASE_INITIATES",
  OYSTER_CARD_PURCHASE_SUCCESSS: "OYSTER_CARD_PURCHASE_SUCCESSS",
  OYSTER_CARD_PURCHASE_FAILURES: "OYSTER_CARD_PURCHASE_FAILURES",
  OYSTER_CARD_FINAL: "OYSTER_CARD_FINAL",
  UPDATE_OYSTER_CARD_STATES: "UPDATE_OYSTER_CARD_STATES",
};
